<a href="https://colab.research.google.com/github/SamiSahbani/Pytorch-Apprentissage-/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

seed = 42



# Numpy
np.random.seed(seed)

# PyTorch CPU
torch.manual_seed(seed)

# PyTorch GPU (si utilisé)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

 #Pour rendre les résultats déterministes (important)
'''
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
 '''

'\ntorch.backends.cudnn.deterministic = True\ntorch.backends.cudnn.benchmark = False\n '

In [4]:
liste=[1,2,3,4,5]
arraye=np.random.rand(2,3)
arraye

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

TENSOR: https://docs.pytorch.org/docs/stable/tensors.html

In [5]:
#Définir un tensor

tensor2d=torch.randn(2,3)
print(tensor2d)
tensor3d=torch.randn(2,3,4)
print(tensor3d)


#CONVERSION NP ARRAY EN TENSOR

tensor=torch.tensor(arraye)
tensor

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])
tensor([[[-0.2483, -1.2082, -0.4777,  0.5201],
         [ 1.6423, -0.1596, -0.4974,  0.4396],
         [ 0.3189, -0.4245,  0.3057, -0.7746]],

        [[ 0.0349,  0.3211,  1.5736, -0.8455],
         [-1.2742,  2.1228, -1.2347, -0.4879],
         [-1.4181,  0.8963,  0.0499,  2.2667]]])


tensor([[0.3745, 0.9507, 0.7320],
        [0.5987, 0.1560, 0.1560]], dtype=torch.float64)

Opérations sur tenseur

In [15]:
#Reshape /View
tens=torch.arange(1,10)
a=tens.reshape(3,3)
'''Attention risque d'erreur si il n'ya pas assez de valeurs pour remplir la matrice'''

#Reshape sans connaître le nombre d'items
b=tens.reshape(3,-1)
b

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])