<a href="https://colab.research.google.com/github/SamiSahbani/Pytorch-Apprentissage-/blob/main/Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import torch
import numpy as np

seed = 42



# Numpy
np.random.seed(seed)

# PyTorch CPU
torch.manual_seed(seed)

# PyTorch GPU (si utilisé)
torch.cuda.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

 #Pour rendre les résultats déterministes (important)
'''
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False
 '''

' \ntorch.backends.cudnn.deterministic = True\ntorch.backends.cudnn.benchmark = False\n '

In [15]:
liste=[1,2,3,4,5]
arraye=np.random.rand(2,3)
arraye

array([[0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643]])

TENSOR: https://docs.pytorch.org/docs/stable/tensors.html

In [21]:
#Définir un tensor

tensor2d=torch.randn(2,3)
print(tensor2d)
tensor3d=torch.randn(2,3,4)
print(tensor3d)


#CONVERSION NP ARRAY EN TENSOR

tensor=torch.tensor(arraye)
tensor

tensor([[-2.4752, -0.9316, -0.1335],
        [ 0.3415, -0.0716, -0.0909]])
tensor([[[ 1.0414, -0.3997, -2.2933,  0.4976],
         [-0.4257, -1.3371, -0.1933,  0.6526],
         [ 0.0358,  0.1206, -0.8057, -0.2076]],

        [[-0.9319, -1.5910, -1.1360, -0.5226],
         [-0.5188, -1.5013, -1.9267,  0.1279],
         [ 1.0229, -0.5558,  0.7043,  0.7099]]])


tensor([[0.8324, 0.2123, 0.1818],
        [0.1834, 0.3042, 0.5248]], dtype=torch.float64)

Opérations sur tenseur